### ISSUE TITLE
Submodule inaccessible

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-tat-eng#1]
The submodule https://gitlab.com/selimcan/tat-eng-texts.git requires login to access, making this pair unbuildable.

Please ensure all submodules can be checked out anonymously.

**Comment by IlnarSelimcan** [comment]
@TinoDidriksen , I can't make those texts public, since they are copyrighted. I just deleted them from this repo.

**Comment by TinoDidriksen** [comment]
Alrighty, that also works. Fixed in commit 0d0a033b81241ec3343538ac9b916ee62c37964f.
